### ISSUE TITLE
Isssues during testing

### ISSUE THREAD

**Issue by sachinpuranik99** [lpj-github-io/MWCNNv2#1]
Hello,

I was trying to experiment with the test code using the examples on the README. It seems that there is some part of the code missing. 
For example: with set68, getting this error

> ModuleNotFoundError: No module named 'data.set68'

Seems like set68 python file is missing. Is it possible to provide the code for the same?

**Comment by Yehaha1** [comment]
Hello! 
 I would like to confirm if you have already resolved the issue? If so, could you please let me know how you managed to solve it?

Best regards.
