### ISSUE TITLE
Where do you insert the Upsample layer for SISR task?

### ISSUE THREAD

**Issue by z0gSh1u** [lpj-github-io/MWCNNv2#5]
That's strange. According to your MWCNN network structure, 3 DWT along with 3 IWT makes the output shape the same as input. However, for super-resolution task, you should perform an upsampling at least.

I've found a Upsampler class using PixelShuffle at `model/common.py`, but its reference seems to be **None**.

Could you please explain this?

```python
def forward(self, x):
        x0 = self.d_l0(self.head(x))
        x1 = self.d_l1(self.DWT(x0))
        x2 = self.d_l2(self.DWT(x1))
        x_ = self.IWT(self.pro_l3(self.DWT(x2))) + x2
        x_ = self.IWT(self.i_l2(x_)) + x1
        x_ = self.IWT(self.i_l1(x_)) + x0
        x = self.tail(self.i_l0(x_)) + x

        return x
```

Also, is there a pretrained model for SISR too?

**Comment by splinter21** [comment]
Bicubic upsampling first.

**Comment by z0gSh1u** [comment]
> Bicubic upsampling first.

that make sense. thx
